CREATE TABLE shop_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    contact_phone VARCHAR(20),
    address VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now()
);

INSERT INTO shop_settings (shop_name) VALUES ('KING CAKE PLACE');
